org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

mod_version=1.4.1
maven_group=com.kielson
archives_base_name=kielsonsapi

fabric_api_version=0.152.2+26.2

modrinth_token=mrp_vtr6EvetDbLOPfq4EgmGTjhproqegINJRbwmUG08xoQbzSL1Hc3zrvQxXV4K
version_type=release